const staticProducts = [
  {
    id: uuidv4(),
    name: 'Laptop ABC',
    brand: 'Brand X',
    price: 1299.99,
    colors: ['#0000FF', '#00FF00', '#FF0000'],
    image: 'https://picsum.photos/200/300?random=1',
    description: 'This is a powerful laptop with advanced features.',
    category: 'Electronics',
    featured: true,
  },
  {
    id: uuidv4(),
    name: 'Smartphone XYZ',
    brand: 'Brand Y',
    price: 699.99,
    colors: ['#FFA500', '#808080', '#FFFFFF'],
    image: 'https://picsum.photos/200/300?random=2',
    description: 'The latest smartphone with a stunning camera and sleek design.',
    category: 'Electronics',
    featured: false,
  },
  {
    id: uuidv4(),
    name: 'Tablet QWE',
    brand: 'Brand Z',
    price: 399.99,
    colors: ['#00FFFF', '#FF00FF', '#FFFF00'],
    image: 'https://picsum.photos/200/300?random=3',
    description: 'A portable and versatile tablet for work and entertainment.',
    category: 'Electronics',
    featured: true,
  },
  {
    id: uuidv4(),
    name: 'Headphones ABC',
    brand: 'Brand H',
    price: 79.99,
    colors: ['#FF4500', '#00CED1', '#8A2BE2'],
    image: 'https://picsum.photos/200/300?random=4',
    description: 'High-quality headphones for an immersive audio experience.',
    category: 'Electronics',
    featured: false,
  },
  {
    id: uuidv4(),
    name: 'Digital Camera LMN',
    brand: 'Brand M',
    price: 499.99,
    colors: ['#008080', '#800080', '#A52A2A'],
    image: 'https://picsum.photos/200/300?random=5',
    description: 'Capture moments with precision using this advanced digital camera.',
    category: 'Electronics',
    featured: true,
  },
  {
    id: uuidv4(),
    name: 'Laptop ABC',
    brand: 'Brand X',
    price: 1299.99,
    colors: ['#0000FF', '#00FF00', '#FF0000'],
    image: 'https://picsum.photos/200/300?random=1',
    description: 'This is a powerful laptop with advanced features.',
    category: 'Electronics',
    featured: true,
  },
  {
    id: uuidv4(),
    name: 'Smartphone XYZ',
    brand: 'Brand Y',
    price: 699.99,
    colors: ['#FFA500', '#808080', '#FFFFFF'],
    image: 'https://picsum.photos/200/300?random=2',
    description: 'The latest smartphone with a stunning camera and sleek design.',
    category: 'Electronics',
    featured: false,
  },
  {
    id: uuidv4(),
    name: 'Tablet QWE',
    brand: 'Brand Z',
    price: 399.99,
    colors: ['#00FFFF', '#FF00FF', '#FFFF00'],
    image: 'https://picsum.photos/200/300?random=3',
    description: 'A portable and versatile tablet for work and entertainment.',
    category: 'Electronics',
    featured: true,
  },
  {
    id: uuidv4(),
    name: 'Headphones ABC',
    brand: 'Brand H',
    price: 79.99,
    colors: ['#FF4500', '#00CED1', '#8A2BE2'],
    image: 'https://picsum.photos/200/300?random=4',
    description: 'High-quality headphones for an immersive audio experience.',
    category: 'Electronics',
    featured: false,
  },
  {
    id: uuidv4(),
    name: 'Digital Camera LMN',
    brand: 'Brand M',
    price: 499.99,
    colors: ['#008080', '#800080', '#A52A2A'],
    image: 'https://picsum.photos/200/300?random=5',
    description: 'Capture moments with precision using this advanced digital camera.',
    category: 'Electronics',
    featured: true,
  },
  {
    id: uuidv4(),
    name: 'Laptop ABC',
    brand: 'Brand X',
    price: 1299.99,
    colors: ['#0000FF', '#00FF00', '#FF0000'],
    image: 'https://picsum.photos/200/300?random=1',
    description: 'This is a powerful laptop with advanced features.',
    category: 'Electronics',
    featured: true,
  },
  {
    id: uuidv4(),
    name: 'Smartphone XYZ',
    brand: 'Brand Y',
    price: 699.99,
    colors: ['#FFA500', '#808080', '#FFFFFF'],
    image: 'https://picsum.photos/200/300?random=2',
    description: 'The latest smartphone with a stunning camera and sleek design.',
    category: 'Electronics',
    featured: false,
  },
  {
    id: uuidv4(),
    name: 'Tablet QWE',
    brand: 'Brand Z',
    price: 399.99,
    colors: ['#00FFFF', '#FF00FF', '#FFFF00'],
    image: 'https://picsum.photos/200/300?random=3',
    description: 'A portable and versatile tablet for work and entertainment.',
    category: 'Electronics',
    featured: true,
  },
  {
    id: uuidv4(),
    name: 'Headphones ABC',
    brand: 'Brand H',
    price: 79.99,
    colors: ['#FF4500', '#00CED1', '#8A2BE2'],
    image: 'https://picsum.photos/200/300?random=4',
    description: 'High-quality headphones for an immersive audio experience.',
    category: 'Electronics',
    featured: false,
  },
  {
    id: uuidv4(),
    name: 'Digital Camera LMN',
    brand: 'Brand M',
    price: 499.99,
    colors: ['#008080', '#800080', '#A52A2A'],
    image: 'https://picsum.photos/200/300?random=5',
    description: 'Capture moments with precision using this advanced digital camera.',
    category: 'Electronics',
    featured: true,
  },
];


console.log(staticProducts); // Print the array to see the complete data.
